#cloud-config
package_update: true
package_upgrade: all

runcmd:
  - apt-get update -y
  - apt-get install -y docker.io nginx
  - systemctl enable docker
  - systemctl start docker
  - systemctl enable nginx
  - systemctl start nginx
  - echo "Hello from ${message}" > /var/www/html/index.html
